# Error handling, "try..catch"

Cho d√π ch√∫ng ta c√≥ gi·ªèi l·∫≠p tr√¨nh ƒë·∫øn ƒë√¢u, ƒë√¥i khi c√°c t·∫≠p l·ªánh c·ªßa ch√∫ng ta c≈©ng c√≥ l·ªói. Ch√∫ng c√≥ th·ªÉ x·∫£y ra do l·ªói c·ªßa ch√∫ng ta, ƒë·∫ßu v√†o c·ªßa ng∆∞·ªùi d√πng kh√¥ng mong mu·ªën, ph·∫£n h·ªìi c·ªßa m√°y ch·ªß b·ªã l·ªói v√† v√¨ h√†ng ng√†n l√Ω do kh√°c.

Th√¥ng th∆∞·ªùng, m·ªôt t·∫≠p l·ªánh "ch·∫øt" (d·ª´ng ngay l·∫≠p t·ª©c) trong tr∆∞·ªùng h·ª£p c√≥ l·ªói, in n√≥ ra console.

Nh∆∞ng c√≥ m·ªôt c√∫ ph√°p construct `try..catch` cho ph√©p "b·∫Øt" c√°c l·ªói v√†, thay v√¨ ch·∫øt, h√£y l√†m ƒëi·ªÅu g√¨ ƒë√≥ h·ª£p l√Ω h∆°n.

## The "try..catch" syntax

C·∫•u tr√∫c `try..catch` c√≥ hai kh·ªëi ch√≠nh: `try` v√† sau ƒë√≥ `catch`:

```js
try {

  // code...

} catch (err) {

  // error handling

}
```

N√≥ ho·∫°t ƒë·ªông nh∆∞ th·∫ø n√†y:

1. ƒê·∫ßu ti√™n, m√£ trong `try {...}` ƒë∆∞·ª£c th·ª±c thi.
2. N·∫øu kh√¥ng c√≥ l·ªói, th√¨ `catch(err)` b·ªã b·ªè qua: vi·ªác th·ª±c thi ƒë·∫øn h·∫øt `try` v√† sau ƒë√≥ nh·∫£y qua `catch`.
3. N·∫øu x·∫£y ra l·ªói, th√¨ vi·ªác th·ª±c thi `try` b·ªã d·ª´ng l·∫°i v√† control s·∫Ω chuy·ªÉn ƒë·∫øn ƒë·∫ßu c·ªßa `catch(err)`. Bi·∫øn `err` (c√≥ th·ªÉ s·ª≠ d·ª•ng b·∫•t k·ª≥ t√™n n√†o cho n√≥) ch·ª©a m·ªôt error object v·ªõi c√°c chi ti·∫øt v·ªÅ nh·ªØng g√¨ ƒë√£ x·∫£y ra.

![](try-catch-flow.png)

V√¨ v·∫≠y, m·ªôt l·ªói b√™n trong kh·ªëi `try {‚Ä¶}` kh√¥ng gi·∫øt ƒë∆∞·ª£c t·∫≠p l·ªánh: ch√∫ng ta c√≥ c∆° h·ªôi x·ª≠ l√Ω n√≥ trong `catch`.

H√£y xem th√™m v√≠ d·ª•.

- M·ªôt v√≠ d·ª• kh√¥ng c√≥ l·ªói: hi·ªÉn th·ªã `alert` `(1)` v√† `(2)`:

    ```js
    try {

      alert('Start of try runs');  // (1) <--

      // ...no errors here

      alert('End of try runs');   // (2) <--

    } catch(err) {

      alert('Catch is ignored, because there are no errors'); // (3)

    }

    alert("...Then the execution continues");
    ```

- M·ªôt v√≠ d·ª• c√≥ l·ªói: hi·ªÉn th·ªã `(1)` v√† `(3)`:

    ```js
    try {

      alert('Start of try runs');  // (1) <--

      lalala; // error, variable is not defined!

      alert('End of try (never reached)');  // (2)

    } catch(err) {

      alert(`Error has occured!`); // (3) <--

    }

    alert("...Then the execution continues");
    ```

<br>

> ---

**üìå `try..catch` ch·ªâ ho·∫°t ƒë·ªông ƒë·ªëi v·ªõi c√°c runtime errors**

ƒê·ªÉ `try..catch` ho·∫°t ƒë·ªông, m√£ ph·∫£i ch·∫°y ƒë∆∞·ª£c. N√≥i c√°ch kh√°c, n√≥ ph·∫£i l√† JavaScript h·ª£p l·ªá.

N√≥ s·∫Ω kh√¥ng ho·∫°t ƒë·ªông n·∫øu m√£ b·ªã sai v·ªÅ m·∫∑t c√∫ ph√°p, v√≠ d·ª•, n√≥ c√≥ d·∫•u ngo·∫∑c nh·ªçn kh√¥ng kh·ªõp:

```js
try {
  {{{{{{{{{{{{
} catch(e) {
  alert("The engine can't understand this code, it's invalid");
}
```

The JavaScript engine tr∆∞·ªõc ti√™n ƒë·ªçc m√£ v√† sau ƒë√≥ ch·∫°y n√≥. C√°c l·ªói x·∫£y ra tr√™n c·ª•m t·ª´ ƒë·ªçc ƒë∆∞·ª£c g·ªçi l√† l·ªói "parse-time" v√† kh√¥ng th·ªÉ ph·ª•c h·ªìi (t·ª´ b√™n trong m√£ ƒë√≥). ƒê√≥ l√† b·ªüi v√¨ engine kh√¥ng th·ªÉ hi·ªÉu ƒë∆∞·ª£c m√£.

V√¨ v·∫≠y, `try..catch` ch·ªâ c√≥ th·ªÉ x·ª≠ l√Ω c√°c l·ªói x·∫£y ra trong m√£ h·ª£p l·ªá. C√°c l·ªói nh∆∞ v·∫≠y ƒë∆∞·ª£c g·ªçi l√† "runtime errors" ho·∫∑c, ƒë√¥i khi, "exceptions".

> ---

<br>
<br>

> ---

**üìå `try..catch` works synchronously**

N·∫øu m·ªôt ngo·∫°i l·ªá x·∫£y ra trong m√£ "scheduled", nh∆∞ trong `setTimeout`, th√¨ `try..catch` s·∫Ω kh√¥ng b·∫Øt ƒë∆∞·ª£c n√≥:

```js
try {
  setTimeout(function() {
    noSuchVariable; // script will die here
  }, 1000);
} catch (e) {
  alert( "won't work" );
}
```

ƒê√≥ l√† b·ªüi v√¨ `try..catch` th·ª±c s·ª± b·ªçc (wraps) cu·ªôc g·ªçi `setTimeout` l·∫°i ƒë·ªÉ l√™n l·ªãch cho h√†m ƒë√≥ (schedules the function). Nh∆∞ng ch√≠nh function n√†y ƒë∆∞·ª£c th·ª±c thi sau ƒë√≥, khi engine ƒë√£ r·ªùi kh·ªèi c·∫•u tr√∫c `try..catch`.

ƒê·ªÉ b·∫Øt m·ªôt ngo·∫°i l·ªá b√™n trong m·ªôt scheduled function, `try..catch` ph·∫£i n·∫±m trong function ƒë√≥:

```js
setTimeout(function() {
  try {    
    noSuchVariable; // try..catch handles the error!
  } catch (e) {
    alert( "error is caught here!" );
  }
}, 1000);
```

> ---

<br>

## Error object

Khi x·∫£y ra l·ªói, JavaScript s·∫Ω t·∫°o m·ªôt ƒë·ªëi t∆∞·ª£ng ch·ª©a c√°c chi ti·∫øt v·ªÅ n√≥. ƒê·ªëi t∆∞·ª£ng sau ƒë√≥ ƒë∆∞·ª£c chuy·ªÉn l√†m ƒë·ªëi s·ªë cho `catch`:

```js
try {
  // ...
} catch(err) { // <-- the "error object", could use another word instead of err
  // ...
}
```

ƒê·ªëi v·ªõi t·∫•t c·∫£ c√°c built-in errors, ƒë·ªëi t∆∞·ª£ng l·ªói trong `catch` block c√≥ hai thu·ªôc t√≠nh ch√≠nh:

**`name`**

Error name. ƒê·ªëi v·ªõi m·ªôt undefined variable ƒë√≥ l√† `"ReferenceError"`.

**`message`**

Tin nh·∫Øn vƒÉn b·∫£n v·ªÅ chi ti·∫øt l·ªói.

C√≥ c√°c thu·ªôc t√≠nh phi ti√™u chu·∫©n (non-standard properties) kh√°c c√≥ s·∫µn trong h·∫ßu h·∫øt c√°c m√¥i tr∆∞·ªùng (environments). M·ªôt trong nh·ªØng s·ª≠ d·ª•ng v√† h·ªó tr·ª£ r·ªông r√£i nh·∫•t l√†:

**`stack`**

NgƒÉn x·∫øp cu·ªôc g·ªçi hi·ªán t·∫°i (Current call stack): m·ªôt string v·ªõi th√¥ng tin v·ªÅ chu·ªói c√°c cu·ªôc g·ªçi l·ªìng nhau d·∫´n ƒë·∫øn l·ªói. ƒê∆∞·ª£c s·ª≠ d·ª•ng cho m·ª•c ƒë√≠ch g·ª° l·ªói.

V√≠ d·ª•:

```js
try {
  lalala; // error, variable is not defined!
} catch(err) {
  alert(err.name); // ReferenceError
  alert(err.message); // lalala is not defined
  alert(err.stack); // ReferenceError: lalala is not defined at ...

  // Can also show an error as a whole
  // The error is converted to string as "name: message"
  alert(err); // ReferenceError: lalala is not defined
}
```

## Using "try..catch"

Ch√∫ng ta h√£y kh√°m ph√° m·ªôt tr∆∞·ªùng h·ª£p s·ª≠ d·ª•ng th·ª±c t·∫ø c·ªßa `try..catch`.

Nh∆∞ ch√∫ng ta ƒë√£ bi·∫øt, JavaScript h·ªó tr·ª£ ph∆∞∆°ng th·ª©c [JSON.parse(str)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse) ƒë·ªÉ ƒë·ªçc JSON-encoded values.

Th√¥ng th∆∞·ªùng, n√≥ ƒë∆∞·ª£c s·ª≠ d·ª•ng ƒë·ªÉ gi·∫£i m√£ d·ªØ li·ªáu nh·∫≠n ƒë∆∞·ª£c qua m·∫°ng, t·ª´ m√°y ch·ªß ho·∫∑c ngu·ªìn kh√°c.

Ch√∫ng ta nh·∫≠n ƒë∆∞·ª£c n√≥ v√† g·ªçi `JSON.parse`, nh∆∞ th·∫ø n√†y:

```js
let json = '{"name":"John", "age": 30}'; // data from the server

let user = JSON.parse(json); // convert the text representation to JS object

// now user is an object with properties from the string
alert( user.name ); // John
alert( user.age );  // 30
```

B·∫°n c√≥ th·ªÉ t√¨m th·∫•y th√¥ng tin chi ti·∫øt h∆°n v·ªÅ JSON trong ch∆∞∆°ng **json**.

** N·∫øu `json` kh√¥ng ƒë√∫ng ƒë·ªãnh d·∫°ng, `JSON.parse` s·∫Ω ph√°t sinh l·ªói, v√¨ v·∫≠y t·∫≠p l·ªánh "ch·∫øt".**

Ch√∫ng ta c√≥ n√™n h√†i l√≤ng v·ªõi ƒëi·ªÅu ƒë√≥? T·∫•t nhi√™n l√† kh√¥ng r·ªìi!

B·∫±ng c√°ch n√†y, n·∫øu c√≥ g√¨ ƒë√≥ kh√¥ng ƒë√∫ng v·ªõi d·ªØ li·ªáu, kh√°ch truy c·∫≠p s·∫Ω kh√¥ng bao gi·ªù bi·∫øt ƒëi·ªÅu ƒë√≥ (tr·ª´ khi h·ªç m·ªü b·∫£ng ƒëi·ªÅu khi·ªÉn d√†nh cho nh√† ph√°t tri·ªÉn). V√† m·ªçi ng∆∞·ªùi th·ª±c s·ª± kh√¥ng th√≠ch khi m·ªôt c√°i g√¨ ƒë√≥ "ch·ªâ ch·∫øt" m√† kh√¥ng c√≥ b·∫•t k·ª≥ th√¥ng b√°o l·ªói n√†o.

H√£y s·ª≠ d·ª•ng `try..catch` ƒë·ªÉ x·ª≠ l√Ω l·ªói:

```js
let json = "{ bad json }";

try {

  let user = JSON.parse(json); // <-- when an error occurs...
  alert( user.name ); // doesn't work

} catch (e) {
  // ...the execution jumps here
  alert( "Our apologies, the data has errors, we'll try to request it one more time." );
  alert( e.name );
  alert( e.message );
}
```

·ªû ƒë√¢y, ch√∫ng ta ch·ªâ s·ª≠ d·ª•ng `catch` block ƒë·ªÉ hi·ªÉn th·ªã th√¥ng b√°o, nh∆∞ng ch√∫ng ta c√≥ th·ªÉ l√†m nhi·ªÅu h∆°n th·∫ø: g·ª≠i y√™u c·∫ßu m·∫°ng m·ªõi, ƒë·ªÅ xu·∫•t m·ªôt gi·∫£i ph√°p thay th·∫ø cho kh√°ch truy c·∫≠p, g·ª≠i th√¥ng tin v·ªÅ l·ªói ƒë·∫øn c∆° s·ªü ghi nh·∫≠t k√Ω, v.v. T·∫•t c·∫£ t·ªët h∆°n nhi·ªÅu so v·ªõi ch·ªâ ch·∫øt.

## Throwing our own errors

ƒêi·ªÅu g√¨ x·∫£y ra n·∫øu `json` ƒë√∫ng v·ªÅ m·∫∑t c√∫ ph√°p, nh∆∞ng kh√¥ng c√≥ thu·ªôc t√≠nh `name` b·∫Øt bu·ªôc?

Nh∆∞ th·∫ø n√†y:

```js
let json = '{ "age": 30 }'; // incomplete data

try {

  let user = JSON.parse(json); // <-- no errors
  alert( user.name ); // no name!

} catch (e) {
  alert( "doesn't execute" );
}
```

·ªû ƒë√¢y `JSON.parse` ch·∫°y b√¨nh th∆∞·ªùng, nh∆∞ng s·ª± v·∫Øng m·∫∑t c·ªßa `name` th·ª±c s·ª± l√† m·ªôt l·ªói cho ch√∫ng ta.

ƒê·ªÉ th·ªëng nh·∫•t x·ª≠ l√Ω l·ªói, ch√∫ng ta s·∫Ω s·ª≠ d·ª•ng to√°n t·ª≠ `throw`.

### "Throw" operator

To√°n t·ª≠ `throw` t·∫°o ra m·ªôt l·ªói.

C√∫ ph√°p l√†:

```js
throw <error object>
```

V·ªÅ m·∫∑t k·ªπ thu·∫≠t, ch√∫ng ta c√≥ th·ªÉ s·ª≠ d·ª•ng b·∫•t c·ª© th·ª© g√¨ nh∆∞ m·ªôt error object. ƒê√≥ c√≥ th·ªÉ l√† m·ªôt nguy√™n th·ªßy, nh∆∞ m·ªôt s·ªë ho·∫∑c m·ªôt chu·ªói, nh∆∞ng t·ªët h∆°n l√† s·ª≠ d·ª•ng c√°c ƒë·ªëi t∆∞·ª£ng, t·ªët nh·∫•t l√† v·ªõi c√°c thu·ªôc t√≠nh `name` v√† `message` (ƒë·ªÉ t∆∞∆°ng th√≠ch v·ªõi c√°c built-in errors).

JavaScript c√≥ nhi·ªÅu built-in constructors cho c√°c l·ªói ti√™u chu·∫©n: `Error`, `SyntaxError`, `ReferenceError`, `TypeError` v√† c√°c lo·∫°i kh√°c. Ch√∫ng ta c√≥ th·ªÉ s·ª≠ d·ª•ng ch√∫ng ƒë·ªÉ t·∫°o c√°c error objects l√† t·ªët.

C√∫ ph√°p c·ªßa ch√∫ng l√†:

```js
let error = new Error(message);
// or
let error = new SyntaxError(message);
let error = new ReferenceError(message);
// ...
```

ƒê·ªëi v·ªõi c√°c built-in errors (kh√¥ng ph·∫£i cho b·∫•t k·ª≥ ƒë·ªëi t∆∞·ª£ng n√†o, ch·ªâ cho c√°c l·ªói), thu·ªôc t√≠nh `name` ch√≠nh x√°c l√† t√™n c·ªßa constructor. V√† `message` ƒë∆∞·ª£c l·∫•y t·ª´ ƒë·ªëi s·ªë.

V√≠ d·ª•:

```js
let error = new Error("Things happen o_O");

alert(error.name); // Error
alert(error.message); // Things happen o_O
```

Ch√∫ng ta h√£y xem lo·∫°i l·ªói n√†o `JSON.parse` t·∫°o ra:

```js
try {
  JSON.parse("{ bad json o_O }");
} catch(e) {
  alert(e.name); // SyntaxError
  alert(e.message); // Unexpected token o in JSON at position 0
}
```

Nh∆∞ ch√∫ng ta c√≥ th·ªÉ th·∫•y, ƒë√≥ l√† m·ªôt `SyntaxError`.

V√† trong tr∆∞·ªùng h·ª£p c·ªßa ch√∫ng ta, s·ª± v·∫Øng m·∫∑t c·ªßa `name` c≈©ng c√≥ th·ªÉ ƒë∆∞·ª£c coi l√† m·ªôt l·ªói c√∫ ph√°p, gi·∫£ s·ª≠ r·∫±ng ng∆∞·ªùi d√πng ph·∫£i c√≥ m·ªôt `name`.

V√¨ v·∫≠y, h√£y n√©m (throw) n√≥:

```js
let json = '{ "age": 30 }'; // incomplete data

try {

  let user = JSON.parse(json); // <-- no errors

  if (!user.name) {
    throw new SyntaxError("Incomplete data: no name"); // (*)
  }

  alert( user.name );

} catch(e) {
  alert( "JSON Error: " + e.message ); // JSON Error: Incomplete data: no name
}
```

Trong d√≤ng `(*)`, to√°n t·ª≠ `throw` t·∫°o ra m·ªôt `SyntaxError` v·ªõi `message` ƒë√£ cho, gi·ªëng nh∆∞ c√°ch JavaScript s·∫Ω t·ª± t·∫°o ra n√≥. Vi·ªác th·ª±c thi `try` ngay l·∫≠p t·ª©c d·ª´ng l·∫°i v√† lu·ªìng ƒëi·ªÅu khi·ªÉn nh·∫£y v√†o `catch`.

B√¢y gi·ªù `catch` ƒë√£ tr·ªü th√†nh m·ªôt n∆°i duy nh·∫•t cho t·∫•t c·∫£ c√°c error handling: c·∫£ cho `JSON.parse` v√† c√°c tr∆∞·ªùng h·ª£p kh√°c.

## Rethrowing

Trong v√≠ d·ª• tr√™n, ch√∫ng ta s·ª≠ d·ª•ng `try..catch` ƒë·ªÉ x·ª≠ l√Ω d·ªØ li·ªáu kh√¥ng ch√≠nh x√°c. Nh∆∞ng c√≥ th·ªÉ l√† *m·ªôt l·ªói kh√¥ng mong mu·ªën kh√°c* x·∫£y ra trong kh·ªëi `try {...}` kh√¥ng? Gi·ªëng nh∆∞ m·ªôt bi·∫øn l√† undefined ho·∫∑c m·ªôt c√°i g√¨ ƒë√≥ kh√°c, kh√¥ng ch·ªâ l√† "d·ªØ li·ªáu kh√¥ng ch√≠nh x√°c".

Nh∆∞ th·∫ø n√†y:

```js
let json = '{ "age": 30 }'; // incomplete data

try {
  user = JSON.parse(json); // <-- forgot to put "let" before user

  // ...
} catch(err) {
  alert("JSON Error: " + err); // JSON Error: ReferenceError: user is not defined
  // (no JSON Error actually)
}
```

T·∫•t nhi√™n, m·ªçi th·ª© ƒë·ªÅu c√≥ th·ªÉ! L·∫≠p tr√¨nh vi√™n l√†m sai. Ngay c·∫£ trong c√°c ti·ªán √≠ch ngu·ªìn m·ªü ƒë∆∞·ª£c s·ª≠ d·ª•ng b·ªüi h√†ng tri·ªáu ng∆∞·ªùi trong nhi·ªÅu th·∫≠p k·ª∑ - ƒë·ªôt nhi√™n m·ªôt l·ªói ƒëi√™n c√≥ th·ªÉ ƒë∆∞·ª£c ph√°t hi·ªán d·∫´n ƒë·∫øn c√°c v·ª• hack kh·ªßng khi·∫øp (gi·ªëng nh∆∞ n√≥ ƒë√£ x·∫£y ra v·ªõi c√¥ng c·ª• `ssh`).

Trong tr∆∞·ªùng h·ª£p c·ªßa ch√∫ng ta, `try..catch` c√≥ nghƒ©a l√† b·∫Øt l·ªói "d·ªØ li·ªáu kh√¥ng ch√≠nh x√°c". Nh∆∞ng theo b·∫£n ch·∫•t c·ªßa n√≥, `catch` l·∫•y *t·∫•t c·∫£* l·ªói t·ª´ `try`. ·ªû ƒë√¢y, n√≥ g·∫∑p m·ªôt l·ªói kh√¥ng mong mu·ªën, nh∆∞ng v·∫´n hi·ªÉn th·ªã c√πng th√¥ng b√°o `"JSON Error"`. ƒêi·ªÅu ƒë√≥ sai v√† c≈©ng l√†m cho m√£ kh√≥ g·ª° l·ªói h∆°n.

May m·∫Øn thay, ch√∫ng ta c√≥ th·ªÉ t√¨m ra l·ªói n√†o ch√∫ng ta nh·∫≠n ƒë∆∞·ª£c, v√≠ d·ª• t·ª´ `name`:

```js
try {
  user = { /*...*/ };
} catch(e) {
  alert(e.name); // "ReferenceError" for accessing an undefined variable
}
```

Quy t·∫Øc r·∫•t ƒë∆°n gi·∫£n:

**Catch ch·ªâ n√™n x·ª≠ l√Ω c√°c l·ªói m√† n√≥ bi·∫øt v√† "rethrow" t·∫•t c·∫£ c√°c l·ªói kh√°c.**

K·ªπ thu·∫≠t "rethrowing" c√≥ th·ªÉ ƒë∆∞·ª£c gi·∫£i th√≠ch chi ti·∫øt h∆°n nh∆∞ sau:

1. B·∫Øt ƒë∆∞·ª£c t·∫•t c·∫£ c√°c l·ªói.
2. Trong kh·ªëi `catch(err) {...}`, ch√∫ng ta ph√¢n t√≠ch ƒë·ªëi t∆∞·ª£ng l·ªói `err`.
2. N·∫øu ch√∫ng ta kh√¥ng bi·∫øt c√°ch x·ª≠ l√Ω n√≥, th√¨ ch√∫ng ta s·∫Ω `throw err`.

Trong ƒëo·∫°n m√£ d∆∞·ªõi ƒë√¢y, ch√∫ng ta s·ª≠ d·ª•ng rethrowing ƒë·ªÉ `catch` ch·ªâ x·ª≠ l√Ω `SyntaxError`:

```js
let json = '{ "age": 30 }'; // incomplete data
try {

  let user = JSON.parse(json);

  if (!user.name) {
    throw new SyntaxError("Incomplete data: no name");
  }

  blabla(); // unexpected error

  alert( user.name );

} catch(e) {

  if (e.name == "SyntaxError") {
    alert( "JSON Error: " + e.message );
  } else {
    throw e; // rethrow (*)
  }

}
```

L·ªói throwing v√†o d√≤ng `(*)` t·ª´ b√™n trong `catch` block "r∆°i ra" c·ªßa `try..catch` v√† c√≥ th·ªÉ b·ªã b·∫Øt b·ªüi m·ªôt outer `try..catch` construct (n·∫øu n√≥ t·ªìn t·∫°i), ho·∫∑c n√≥ gi·∫øt ch·∫øt k·ªãch b·∫£n.

V√¨ v·∫≠y, kh·ªëi `catch` th·ª±c s·ª± ch·ªâ x·ª≠ l√Ω c√°c l·ªói m√† n√≥ bi·∫øt c√°ch x·ª≠ l√Ω v√† "b·ªè qua" t·∫•t c·∫£ c√°c l·ªói kh√°c.

V√≠ d·ª• d∆∞·ªõi ƒë√¢y minh h·ªça c√°ch c√°c l·ªói nh∆∞ v·∫≠y c√≥ th·ªÉ b·ªã b·∫Øt b·ªüi m·ªôt c·∫•p ƒë·ªô n·ªØa c·ªßa `try..catch`:

```js
function readData() {
  let json = '{ "age": 30 }';

  try {
    // ...
    blabla(); // error!
  } catch (e) {
    // ...
    if (e.name != 'SyntaxError') {
      throw e; // rethrow (don't know how to deal with it)
    }
  }
}

try {
  readData();
} catch (e) {
  alert( "External catch got: " + e ); // caught it!
}
```

·ªû ƒë√¢y `readData` ch·ªâ bi·∫øt c√°ch x·ª≠ l√Ω `SyntaxError`, trong khi `try..catch` b√™n ngo√†i bi·∫øt c√°ch x·ª≠ l√Ω m·ªçi th·ª©.

## try..catch..finally

ƒê·ª£i ƒë√£, ƒë√≥ kh√¥ng ph·∫£i l√† t·∫•t c·∫£.

C·∫•u tr√∫c `try..catch` c√≥ th·ªÉ c√≥ th√™m m·ªôt m·ªánh ƒë·ªÅ m√£: `finally`.

N·∫øu n√≥ t·ªìn t·∫°i, n√≥ ch·∫°y trong m·ªçi tr∆∞·ªùng h·ª£p:

- sau `try`, n·∫øu kh√¥ng c√≥ l·ªói,
- sau `catch`, n·∫øu c√≥ l·ªói.

C√∫ ph√°p m·ªü r·ªông tr√¥ng nh∆∞ th·∫ø n√†y:

```js
try {
   ... try to execute the code ...
} catch(e) {
   ... handle errors ...
} finally {
   ... execute always ...
}
```

H√£y th·ª≠ ch·∫°y m√£ n√†y:

```js
try {
  alert( 'try' );
  if (confirm('Make an error?')) BAD_CODE();
} catch (e) {
  alert( 'catch' );
} finally {
  alert( 'finally' );
}
```

M√£ n√†y c√≥ hai c√°ch th·ª±c hi·ªán:

1. N·∫øu b·∫°n tr·∫£ l·ªùi "Yes" cho "Make an error?", Sau ƒë√≥ `try -> catch -> finally`.
2. N·∫øu b·∫°n n√≥i "No", th√¨ `try -> finally`.

M·ªánh ƒë·ªÅ `finally` th∆∞·ªùng ƒë∆∞·ª£c s·ª≠ d·ª•ng khi ch√∫ng ta b·∫Øt ƒë·∫ßu l√†m m·ªôt c√°i g√¨ ƒë√≥ tr∆∞·ªõc khi `try..catch` v√† mu·ªën ho√†n thi·ªán n√≥ trong m·ªçi tr∆∞·ªùng h·ª£p c·ªßa k·∫øt qu·∫£.

Ch·∫≥ng h·∫°n, ch√∫ng ta mu·ªën ƒëo th·ªùi gian m√† m·ªôt Fibonacci numbers function `fib(n)` c·∫ßn. ƒê∆∞∆°ng nhi√™n, ch√∫ng ta c√≥ th·ªÉ b·∫Øt ƒë·∫ßu ƒëo tr∆∞·ªõc khi n√≥ ch·∫°y v√† k·∫øt th√∫c sau ƒë√≥. Nh∆∞ng n·∫øu c√≥ l·ªói trong khi g·ªçi h√†m th√¨ sao? C·ª• th·ªÉ, vi·ªác tri·ªÉn khai `fib(n)` trong ƒëo·∫°n m√£ d∆∞·ªõi ƒë√¢y tr·∫£ v·ªÅ l·ªói cho c√°c s·ªë √¢m ho·∫∑c kh√¥ng nguy√™n.

M·ªánh ƒë·ªÅ `finally` l√† m·ªôt n∆°i tuy·ªát v·ªùi ƒë·ªÉ ho√†n th√†nh c√°c ph√©p ƒëo b·∫•t k·ªÉ l√† g√¨.

·ªû ƒë√¢y `finally` ƒë·∫£m b·∫£o r·∫±ng th·ªùi gian s·∫Ω ƒë∆∞·ª£c ƒëo ch√≠nh x√°c trong c·∫£ hai t√¨nh hu·ªëng -- trong tr∆∞·ªùng h·ª£p th·ª±c hi·ªán th√†nh c√¥ng `fib` v√† trong tr∆∞·ªùng h·ª£p c√≥ l·ªói trong ƒë√≥:

```js
let num = +prompt("Enter a positive integer number?", 35)

let diff, result;

function fib(n) {
  if (n < 0 || Math.trunc(n) != n) {
    throw new Error("Must not be negative, and also an integer.");
  }
  return n <= 1 ? n : fib(n - 1) + fib(n - 2);
}

let start = Date.now();

try {
  result = fib(num);
} catch (e) {
  result = 0;
} finally {
  diff = Date.now() - start;
}

alert(result || "error occured");

alert( `execution took ${diff}ms` );
```

B·∫°n c√≥ th·ªÉ ki·ªÉm tra b·∫±ng c√°ch ch·∫°y m√£ b·∫±ng c√°ch nh·∫≠p `35` v√†o `prompt` -- n√≥ th·ª±c thi b√¨nh th∆∞·ªùng, `finally` sau `try`. V√† sau ƒë√≥ nh·∫≠p `-1` -- s·∫Ω c√≥ m·ªôt l·ªói ngay l·∫≠p t·ª©c, vi·ªác th·ª±c thi s·∫Ω m·∫•t `0ms`. C·∫£ hai ph√©p ƒëo ƒë·ªÅu ƒë∆∞·ª£c th·ª±c hi·ªán ch√≠nh x√°c.

N√≥i c√°ch kh√°c, c√≥ th·ªÉ c√≥ hai c√°ch ƒë·ªÉ tho√°t kh·ªèi h√†m: ho·∫∑c l√† `return` ho·∫∑c `throw`. M·ªánh ƒë·ªÅ `finally` x·ª≠ l√Ω c·∫£ hai.

<br>

> ---

**üìå C√°c bi·∫øn l√† c·ª•c b·ªô b√™n trong `try..catch..finally`**

Xin l∆∞u √Ω r·∫±ng c√°c bi·∫øn `result` v√† `diff` trong ƒëo·∫°n m√£ tr√™n ƒë∆∞·ª£c khai b√°o *tr∆∞·ªõc* `try..catch`.

M·∫∑t kh√°c, n·∫øu `let` ƒë∆∞·ª£c t·∫°o b√™n trong kh·ªëi `{...}`, n√≥ s·∫Ω ch·ªâ hi·ªÉn th·ªã b√™n trong kh·ªëi.

> ---

<br>
<br>

> ---

**üìå `finally` and `return`**

M·ªánh ƒë·ªÅ `finally` ho·∫°t ƒë·ªông cho *any* exit t·ª´ `try..catch`. ƒêi·ªÅu ƒë√≥ bao g·ªìm m·ªôt `return` r√µ r√†ng.

Trong v√≠ d·ª• d∆∞·ªõi ƒë√¢y, c√≥ m·ªôt `return` trong `try`. Trong tr∆∞·ªùng h·ª£p n√†y, `finally` ƒë∆∞·ª£c th·ª±c thi ngay tr∆∞·ªõc khi control quay tr·ªü l·∫°i outer code.

```js
function func() {

  try {
    return 1;

  } catch (e) {
    /* ... */
  } finally {
    alert( 'finally' );
  }
}

alert( func() ); // first works alert from finally, and then this one
```

> ---

<br>
<br>

> ---

**üìå `try..finally`**

C·∫•u tr√∫c `try..finally`, kh√¥ng c√≥ m·ªánh ƒë·ªÅ `catch`, c≈©ng h·ªØu √≠ch. Ch√∫ng ta √°p d·ª•ng n√≥ khi ch√∫ng ta kh√¥ng mu·ªën x·ª≠ l√Ω l·ªói ngay t·∫°i ƒë√¢y, nh∆∞ng mu·ªën ch·∫Øc ch·∫Øn r·∫±ng c√°c quy tr√¨nh m√† ch√∫ng ta ƒë√£ b·∫Øt ƒë·∫ßu ƒë∆∞·ª£c ho√†n t·∫•t.

```js
function func() {
  // start doing something that needs completion (like measurements)
  try {
    // ...
  } finally {
    // complete that thing even if all dies
  }
}
```

Trong ƒëo·∫°n m√£ tr√™n, m·ªôt l·ªói b√™n trong `try` lu√¥n lu√¥n r∆°i ra, b·ªüi v√¨ kh√¥ng c√≥ `catch`. Nh∆∞ng `finally` ho·∫°t ƒë·ªông tr∆∞·ªõc khi d√≤ng th·ª±c thi nh·∫£y ra ngo√†i.

> ---

<br>

## Global catch

<br>

> ---

**üìå Environment-specific**

Th√¥ng tin t·ª´ ph·∫ßn n√†y kh√¥ng ph·∫£i l√† m·ªôt ph·∫ßn c·ªßa core JavaScript.

> ---

<br>

Ch√∫ng ta h√£y t∆∞·ªüng t∆∞·ª£ng r·∫±ng ch√∫ng ta ƒë√£ c√≥ m·ªôt l·ªói nghi√™m tr·ªçng b√™n ngo√†i `try..catch`, v√† k·ªãch b·∫£n ƒë√£ ch·∫øt. Gi·ªëng nh∆∞ m·ªôt l·ªói l·∫≠p tr√¨nh ho·∫∑c m·ªôt c√°i g√¨ ƒë√≥ kh·ªßng khi·∫øp.

C√≥ c√°ch n√†o ƒë·ªÉ ph·∫£n ·ª©ng v·ªÅ nh·ªØng s·ª± c·ªë nh∆∞ v·∫≠y kh√¥ng? Ch√∫ng ta c√≥ th·ªÉ mu·ªën log l·∫°i l·ªói, hi·ªÉn th·ªã m·ªôt c√°i g√¨ ƒë√≥ cho ng∆∞·ªùi d√πng (th√¥ng th∆∞·ªùng h·ªç kh√¥ng th·∫•y th√¥ng b√°o l·ªói), v.v.

Kh√¥ng c√≥ g√¨ trong ƒë·∫∑c t·∫£, nh∆∞ng environments th∆∞·ªùng cung c·∫•p n√≥, b·ªüi v√¨ n√≥ th·ª±c s·ª± h·ªØu √≠ch. Ch·∫≥ng h·∫°n, [Node.JS c√≥ [process.on('uncaughtException')](https://nodejs.org/api/process.html#process_event_uncaughtexception) cho ƒëi·ªÅu ƒë√≥. V√† trong tr√¨nh duy·ªát, ch√∫ng ta c√≥ th·ªÉ g√°n m·ªôt h√†m cho thu·ªôc t√≠nh [window.onerror](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) ƒë·∫∑c bi·ªát. N√≥ s·∫Ω ch·∫°y trong tr∆∞·ªùng h·ª£p l·ªói Kh√¥ng b·ªã b·∫Øt.

C√∫ ph√°p:

```js
window.onerror = function(message, url, line, col, error) {
  // ...
};
```

**`message`**

Error message.

**`url`**

URL c·ªßa t·∫≠p l·ªánh n∆°i x·∫£y ra l·ªói.

**`line`, `col`**

S·ªë d√≤ng v√† c·ªôt n∆°i x·∫£y ra l·ªói.

**`error`**

Error object.

V√≠ d·ª•:

```html
<script>
  window.onerror = function(message, url, line, col, error) {
    alert(`${message}\n At ${line}:${col} of ${url}`);
  };

  function readData() {
    badFunc(); // Whoops, something went wrong!
  }

  readData();
</script>
```

Vai tr√≤ c·ªßa global handler `window.onerror` th∆∞·ªùng kh√¥ng ph·ª•c h·ªìi vi·ªác th·ª±c thi t·∫≠p l·ªánh -- ƒëi·ªÅu ƒë√≥ c√≥ l·∫Ω l√† kh√¥ng th·ªÉ trong tr∆∞·ªùng h·ª£p c√≥ l·ªói l·∫≠p tr√¨nh, nh∆∞ng ƒë·ªÉ g·ª≠i th√¥ng b√°o l·ªói cho nh√† ph√°t tri·ªÉn.

Ngo√†i ra c√≤n c√≥ c√°c d·ªãch v·ª• web cung c·∫•p ghi nh·∫≠t k√Ω l·ªói cho c√°c tr∆∞·ªùng h·ª£p nh∆∞ v·∫≠y, nh∆∞ <https://errorception.com> ho·∫∑c <http://www.muscula.com>.

H·ªç l√†m vi·ªác nh∆∞ th·∫ø n√†y:

1. Ch√∫ng ta ƒëƒÉng k√Ω t·∫°i d·ªãch v·ª• v√† nh·∫≠n m·ªôt ƒëo·∫°n m√£ JS (ho·∫∑c m·ªôt script URL) t·ª´ h·ªç ƒë·ªÉ ch√®n v√†o c√°c trang.
2. JS script ƒë√≥ c√≥ h√†m `window.onerror` t√πy ch·ªânh.
3. Khi x·∫£y ra l·ªói, n√≥ s·∫Ω g·ª≠i m·ªôt y√™u c·∫ßu m·∫°ng v·ªÅ n√≥ ƒë·∫øn d·ªãch v·ª•.
4. Ch√∫ng ta c√≥ th·ªÉ ƒëƒÉng nh·∫≠p v√†o giao di·ªán web d·ªãch v·ª• v√† th·∫•y l·ªói.

## T√≥m l∆∞·ª£c

C·∫•u tr√∫c `try..catch` cho ph√©p x·ª≠ l√Ω c√°c runtime errors. N√≥ th·ª±c s·ª± cho ph√©p try running the code v√† catch errors c√≥ th·ªÉ x·∫£y ra trong ƒë√≥.

C√∫ ph√°p l√†:

```js
try {
  // run this code
} catch(err) {
  // if an error happened, then jump here
  // err is the error object
} finally {
  // do in any case after try/catch
}
```

C√≥ th·ªÉ kh√¥ng c√≥ ph·∫ßn `catch` ho·∫∑c kh√¥ng `finally`, v√¨ v·∫≠y `try..catch` v√† `try..finally` c≈©ng h·ª£p l·ªá.

C√°c error objects c√≥ c√°c thu·ªôc t√≠nh sau:

- `message` -- th√¥ng b√°o l·ªói c√≥ th·ªÉ ƒë·ªçc ƒë∆∞·ª£c.
- `name` -- the string c√≥ t√™n l·ªói (error constructor name).
- `stack` (non-standard) -- ngƒÉn x·∫øp t·∫°i th·ªùi ƒëi·ªÉm t·∫°o l·ªói.

Ch√∫ng ta c≈©ng c√≥ th·ªÉ t·ª± t·∫°o ra c√°c l·ªói c·ªßa m√¨nh b·∫±ng c√°ch s·ª≠ d·ª•ng to√°n t·ª≠ `throw`. V·ªÅ m·∫∑t k·ªπ thu·∫≠t, ƒë·ªëi s·ªë c·ªßa `throw` c√≥ th·ªÉ l√† b·∫•t c·ª© ƒëi·ªÅu g√¨, nh∆∞ng th√¥ng th∆∞·ªùng, ƒë√≥ l√† m·ªôt ƒë·ªëi t∆∞·ª£ng l·ªói th·ª´a h∆∞·ªüng t·ª´ built-in `Error` class. Th√™m v·ªÅ extending errors trong ch∆∞∆°ng ti·∫øp theo.

Rethrowing l√† m·ªôt m√¥ h√¨nh x·ª≠ l√Ω l·ªói c∆° b·∫£n: m·ªôt kh·ªëi `catch` th∆∞·ªùng mong ƒë·ª£i v√† bi·∫øt c√°ch x·ª≠ l√Ω lo·∫°i l·ªói c·ª• th·ªÉ, v√¨ v·∫≠y n√≥ n√™n ƒëi·ªÅu ch·ªânh l·∫°i c√°c l·ªói m√† n√≥ kh√¥ng bi·∫øt.

Ngay c·∫£ khi ch√∫ng ta kh√¥ng c√≥ `try..catch`, h·∫ßu h·∫øt c√°c environments ƒë·ªÅu cho ph√©p thi·∫øt l·∫≠p m·ªôt "global" error handler ƒë·ªÉ b·∫Øt l·ªói "r∆°i ra (fall out)". Trong tr√¨nh duy·ªát ƒë√≥ l√† `window.onerror`.
